// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config"
import { defineConfig } from "prisma/config"

const DB_URL = process.env.DATABASE_URL

if (!DB_URL)
  throw new Error("DATABASE_URL is undefine")

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: DB_URL,
  },
})
